name: docs

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: "Build and deploy documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: Set up Python 3.11
        uses: "actions/setup-python@v4"
        with:
            python-version: 3.11
            cache: 'pip'
      - run: pip install -r docs/requirements.txt
      - name: Build documentation
        run: cd docs && make html
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs/_build/html'
          destination-github-username: 'jaxopt'
          destination-repository-name: 'jaxopt.github.io'
          user-email: jaxopt@google.com
          target-branch: main
          target-directory: dev
